using Godot;
using System;

public class Global : Node
{
	public static int WordsTyped = 0;
	public static Vector2 pos = new Vector2(638, 628);
	public static bool is_dead = false;
	
public static string[] easy_words = {
	"great",
	"animal",
	"keep",
	"name",
	"away",
	"together",
	"been",
	"should",
	"four",
	"every",
	"number",
	"hand",
	"again",
	"before",
	"over",
	"make",
	"grow",
	"soon",
	"begin",
	"animal",
	"your",
	"thing",
	"mean",
	"write",
	"while",
	"letter",
	"before",
	"name",
	"night",
	"must",
	"mean",
	"home",
	"which",
	"time",
	"left",
	"make",
	"year",
	"around",
	"story",
	"sometimes",
	"group",
	"took",
	"begin",
	"mother",
	"river",
	"earth",
	"some",
	"point",
	"give",
	"went",
	"give",
	"something",
	"without",
	"study",
	"miss",
	"this",
	"really",
	"family",
	"carry",
	"know",
	"took",
	"read",
	"began",
	"year",
	"feet",
	"father",
	"heart",
	"can",
	"grow",
	"but",
	"and",
	"because",
	"brought",
	"show",
	"running",
	"deck",
	"watch",
	"sit",
	"laugh",
	"drink",
	"laptop",
	
};

public static string[] hard_words = {
"depth", "forgetting", "example", "educate",
"entire", "horizon", "freight", "earliest",
"threat", "relieve", "muscle", "meant",
"exchange", "securing", "obedient", "unsanitary",
"leisure", "crypt", "supervisor", "persuade",
"glamorous", "optimistic", "envious", "controversy",
"deficiency", "schedule", "characteristic",	"environment",
"amusement", "criticize", "venom", "awkward",
"arrangement", "considerable", "barometer", "vulnerable",
"mercenary", "plaintiff", "omitted", "deterrent",
"cameos", "malicious", "obscure", "propeller",
"perceived", "taboo", "technology", "surmise",
"internally", "specific", "protein", "criminal",
"precipitate", "forgery", "unbelievable", "unduly",
"annoyance", "vessel", "insufficient", "capably",
"belligerent", "amnesty", "snobbery", "applicant",
"anxious", "fashionable", "machinery", "laboratory",
"shuddering", "sacrifice", "fibrous", "escalator",
"privilege", "burglary", "melodious", "embargo",
"outrageous", "rectangular", "honorary", "minimize",
"contrary", "passageway", "vertigo", "malady",
"lucrative", "extraordinary", "abstain", "procrastinate",
"serviceable", "parliament", "necessity", "recurrent",
"ominous", "permeate", "religious", "occurred",
"prestigious", "scandalized", "voracious", "universal",
"transient", "meticulous", "personification", "inevitable",
"vigilant", "interrogate", "malignant", "benevolent",
"consequence", "unenforceable", "nostalgia", "omnipotent",
"vivacious", "precocious", "indulgence", "vulnerable",
"vacillate", "inconvenience", "potpourri", "ubiquitous",
"phenomenon", "caricature", "surveillance", "metamorphosis"
};
}
